### ISSUE TITLE
TS client should emit parsed values instead of strings

### ISSUE THREAD

**Issue by icehaunter** [electric-sql/electric-next#164]
Continuing on from #100, and blocked by #163.

The TS client should parse string values coming over the wire and emit "proper" types. The set of parsers should be pluggable, so that anyone can provide their own implementation if they need something specific (or disable it if they want plain strings).

The default parsed set for now should be:
- `int2`, `int4`, `float8` into `number`
- `bool` into `boolean`
- `int8` into `bigint`
- `array of ...` into an array of strings or further parsed implementation
- `json`, `jsonb` into actual JS object

**Comment by alco** [comment]
If the parsing happens on the client and the default parser aims to decode all compatible values into JS, `float4` should also be decoded into `number`. Why not?
- JS `number` can fit all values of PG `float4`, so it stands apart from `int8` and `numeric`
- we're not talking about replicating server updates into a local DB here, so maintaining perfect type parity is not a concern
- it is actually possible to do float32 arithmetic in JS and get a number representable in float32 in the end. See https://blog.mozilla.org/javascript/2013/11/07/efficient-float32-arithmetic-in-javascript/
- just due to the fact that we're talking about a TS client, a floating-point number is expected to be decoded into a JS number, regardless of its original precision

**Comment by kevin-dp** [comment]
@alco As we discovered in the original Electric, handling 32 bit floats in JavaScript can be very confusing. I would argue not to do this automatically to avoid confusion. Instead, let users handle it explicitly if they need to such that they understand the behavior they will observe.

**Comment by alco** [comment]
> @alco As we discovered in the original Electric, handling 32 bit floats in JavaScript can be very confusing. I would argue not to do this automatically to avoid confusion. Instead, let users handle it explicitly if they need to such that they understand the behavior they will observe.

What we're discussing here is a different issue from what we had in the original Electric. There our goal was to preserve values in storage between Postgres and SQLite. We would still decode `float4` numbers that were stored in SQLite to JS numbers when reading them from the database, wouldn't we?

Now, in this issue we discuss decoding values of those Postgres types that have a well-defined equivalent in JS. While we choose not to decode `numeric` because there's no builtin infinite-precision decimal type in JS, we can decode `float4` to a JS number with no loss of precision. It's not a point of contention, IMO, because in order to do anything useful with a string-encoded `float4` number in JS (i.e. arithmetic), one has to decode it into a JS number.

Take any random JSON API intended for consumption by a JS client. For all we know, some or all floating-point numbers in it could have originated from `float4` columns in Postgres. But that's irrelevant for the JS client.

For the other use cases such as writing values from our HTTP API directly to PGLite, or decoding them differently in a client written in a different language, there's still the option of doing no decoding at all. But when we are discussing what to decode in JS, I believe it would be consistent to treat `float4` values the same as `float8`.
