### ISSUE TITLE
Clients should just ask for the `url` to a shape (not `baseURL` and `table` we currently have)

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric-next#204]
I've been exploring how apps can query for shapes. I've discovered three patterns so far:

1. Client just asks for the shape and the API proxies it e.g.

```ts
// Client
{
    shape: { table: `contacts` },
    baseUrl: `http://localhost:5173/shape-proxy`,
}

// Server
export async function handler({ params, request }) {
  const requestUrl = new URL(request.url)
  const { table } = params
  
  // Validate user can request this shape
  if (checkShapeAccessPermission(user, shapeDef)) {
    const originUrl = new URL(`http://localhost:3000/v1/shape/${table}`)
    requestUrl.searchParams.forEach((value, key) => {
      originUrl.searchParams.set(key, value)
    })
    return await fetch(originUrl.toString())
  } else {
    // 403 access denied
  }
}
```

2. Client asks for shape and API adds where clauses to restrict access e.g. in this case by the organization the user belongs to.

```ts
// Client
{
    shape: { table: `contacts` },
    baseUrl: `http://localhost:5173/shape-proxy`,
}

// Server
export async function handler({ params, request }) {
  const requestUrl = new URL(request.url)
  const { table } = params
  
  // Validate user can request this shape
  if (checkShapeAccessPermission(user, shapeDef)) {
    const originUrl = new URL(`http://localhost:3000/v1/shape/${table}`)
    requestUrl.searchParams.forEach((value, key) => {
      originUrl.searchParams.set(key, value)
    })

    // Restrict to contacts within the organization the user belongs to.
    originUrl.searchParams.set(`where`, `org_id = ${user.org_id}`)
    return await fetch(originUrl.toString())
  } else {
    // 403 access denied
  }
}
```

3. The third option isn't supported by our shape definition but which is that people could use normal REST API patterns e.g. `/api/contacts`. Then the API would just proxy that to the right URL on electric along with query parameters like `?offset=STRING`. 

In order to support this third pattern, users should just directly specify the backend URL to hit for a shape e.g.

```ts
const shapeDef = {
  url: `/api/shape/contacts`
}
```

This is also more elegant as it combines the `baseURL` and `shape` object into just the `url`.

**Comment by balegas** [comment]
> This is also more elegant as it combines the baseURL and shape object into just the url.

Sounds good, the url is just an url. Let the layers above build the URL. Under 3. clients don't have to come-up with the shape definition is just a request to an API.

It is curious that the parameters still need to follow protocol. Eventually the server could know more about the session and even hide the details about the parameters. 

I am now thinking that we should just send down with a response the next URL to fetch, instead of requiring the client figuring it out. This would abstract the parameters behind the URL too.

**Comment by KyleAMathews** [comment]
> I am now thinking that we should just send down with a response the next URL to fetch, instead of requiring the client figuring it out. This would abstract the parameters behind the URL too.

Very interesting! Yeah, it makes sense — it's just a daisy chain you follow 🤔

The proxy gets a bit more complex though. Right now the pattern for the client is — stable URL path w/ changing `offset` & `shapeId` query params. In your idea, the proxy creates a new URL every time that the client reads and calls again.

I don't know if that helps much though? `offset` and `shapeId` are abstract values and any other scheme would end up very similar.

**Comment by balegas** [comment]
I was thinking on the use-cases of 3:
1. I like the possibility of having and endpoint that omits the shape definition parameters in a friendly way --- After the first call, you get the parameters to follow. perfect. (1)
2. In the spirit of allowing developers to build generic proxy apis, It seemed a bit of a limitation that endpoints still need to leak the sync-engine parameters. The reason I think generic proxy is important is because many devs will want to have a sort of backend in front of shape-requests.

The client is building the url by reading the headers `x-electric-shape-id` and `x-electric-chunk-last-offset` in a deterministic way, so it's equivalent to having url. But the url can be manipulated by the proxy, while the parameters don't.
 - I think this is consistent with replacing `baseUrl` and `shape` with `url`
 - Maybe its a `x-electric-proxy-url` that the protocol understands and subsumes the other parameters if present -- this gives optionality without commitment.

>  In your idea, the proxy creates a new URL every time that the client reads and calls again.

right, if there is some url-creation logic there needs to some introspection (even for the base REST case). I believe this proxy would be doing a lot of other things. 

(1) building this through the proxy is a bit laborious and error-prone, in the future we could build a REST-api generator from registered shape definitions.

**Comment by KyleAMathews** [comment]
Cool yeah we'll see if anyone wants that in the future. A proxy right now is all of 4-5 lines of code and I suspect that's all most people will want.

**Comment by balegas** [comment]
yeah, entertaining the though that _shape is just an url_. Keep it simple

**Comment by chasers** [comment]
> in the future we could build a REST-api generator from registered shape definitions

btw lots of parallels with [PostgREST](https://docs.postgrest.org/en/v12/references/api/tables_views.html) here

eg `http://localhost:3000/people?age=gte.18&student=is.true`
